import React, { useState } from "react";
import Navbar from "@/components/Navbar/Navbar";
import Sidebar from "@/components/Sidebar/Sidebar";
import Head from "next/head";

export default function Home() {
  const [isSidebarOpen, setSidebarOpen] = useState(false);

  function sidebarHandler() {
    setSidebarOpen(!isSidebarOpen);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar
        isSidebarOpen={isSidebarOpen}
        onClickToggleNavbar={sidebarHandler}
      />
      <div className="flex pt-16 overflow-hidden bg-gray-50 dark:bg-gray-900">
        <Sidebar isSidebarOpen={isSidebarOpen} activeMenu="dashboard" />
        <div
          id="main-content"
          className="relative w-full h-full overflow-y-auto bg-gray-50 lg:ml-64 dark:bg-gray-900"
        >
          <div className="p-3">CONTENT DASHBOARD</div>
        </div>
      </div>
    </>
  );
}
